### ISSUE TITLE
Python3 dict.iterims not working -> replace with dict.items

### ISSUE THREAD

**Issue by pstauffer** [confirm/ansibleci#39]
Python 3 renamed dict.iteritems -> dict.items
Remove dict.iteritems(), dict.iterkeys(), and dict.itervalues().
Instead: use dict.items(), dict.keys(), and dict.values() respectively.

https://wiki.python.org/moin/Python3.0

``` python
The command "ls -l ../ansibleci" exited with 0.
0.10s$ python ../ansibleci/test.py
Traceback (most recent call last):
  File "../ansibleci/test.py", line 35, in <module>
    main()
  File "../ansibleci/test.py", line 19, in main
    config = Config(load_defaults=True)
  File "/home/travis/build/pstauffer/ansibleci/ansibleci/config.py", line 35, in __init__
    self.add_module(ansibleci.defaults)
  File "/home/travis/build/pstauffer/ansibleci/ansibleci/config.py", line 65, in add_module
    for key, value in module.__dict__.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
The command "python ../ansibleci/test.py" exited with 1.
```

**Comment by domibarton** [comment]
Don't know if we're really Python 3 ready.
We need to check all Python modules we're using first, for example:
- PyYAML
- Ansible (future syntax check)

I think we shouldn't make this mandatory for v1.0

**Comment by pstauffer** [comment]
Agree.
